version: '3.3'
services:
  app_curotec:
    container_name: app_curotec
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend/:/var/www
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.17.0.1
    networks:
      - laravel

  postgres_curotec:
    image: 'postgres:latest'
    container_name: postgres_curotec
    restart: always
    ports:
        - '5433:5432'
    environment:
        POSTGRES_DB: 'curotecschema'
        POSTGRES_USER: 'curotec'
        POSTGRES_PASSWORD: 987654321
    volumes:
        - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    privileged: true  
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/ 
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge